# Generated by Django 2.0.1 on 2018-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.CharField(blank=True, max_length=50)),
                ('touser', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=100)),
                ('permission', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.TextField(blank=True, max_length=100)),
                ('typeof', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
