# Generated by Django 2.0.1 on 2018-03-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='testimageloc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
