# Generated by Django 2.0.1 on 2018-03-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
