# Generated by Django 2.0.1 on 2018-03-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_images_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='imagesmodel',
        ),
    ]
